### ISSUE TITLE
Metric file not found under OS X El Capitan with MacTex2015

### ISSUE THREAD

**Issue by DaPhil** [sebschub/FontPro#49] opened 2015-10-02 08:13 UTC
I encounter a problem with the MyriadPro and MinionPro metric files under a clean install of Mac OS X El Capitan with a fresh MacTex2015. Installing the fonts as described works properly (despite many error messages during installation which was already addressed by another issue report). However, compiling a tex file with MyriadPro or MinionPro leads to errors whenever certain font sizes are in use, e.g.

```
\documentclass{scrreprt}
\usepackage{MyriadPro}
\renewcommand{\familydefault}{\sfdefault}
\begin{document}
\chapter{My very first chapter} % Not visible
Some words... % Correct font
\end{document}
```

produces the error message

```
./main.tex:12: Font OT1/MyriadPro-OsF/bx/n/20.74=MyriadPro-Bold- at 20.74pt not loadable: Metric (TFM) file not found.
<to be read again> 
                   relax 
l.12 \chapter{My very first chapter}

./main.tex:12: Font \OT1/MyriadPro-OsF/b/n/20.74=nullfont not loadable: Metric (TFM) file not found.
<to be read again> 
                   \relax 
l.12 \chapter{My very first chapter}
```

I get similar error messages when I try to use MinionPro also for chapters.

**Comment by robsalasco** [comment] 2016-03-18 19:14
I have the same error!

**Comment by sebschub** [comment] 2017-05-21 19:22
Could you test again with MacTeX 2016? Other people reported that it worked. Without a Mac and MacTeX I cannot reproduce the error and, thus, hope that it is fixed in 2016. Please feel free to reopen.

**Closed by sebschub** 2017-05-21 19:22 UTC

**Comment by GiacomoPope** [comment] 2020-04-01 17:25
This seems to be the error I am having
